// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "bluebell/models"

	mock "github.com/stretchr/testify/mock"
)

// UserLogicInterface is an autogenerated mock type for the UserLogicInterface type
type UserLogicInterface struct {
	mock.Mock
}

// Login provides a mock function with given fields: p
func (_m *UserLogicInterface) Login(p *models.ParamLogin) (*models.User, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.ParamLogin) (*models.User, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(*models.ParamLogin) *models.User); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.ParamLogin) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignUp provides a mock function with given fields: p
func (_m *UserLogicInterface) SignUp(p *models.ParamSignUp) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ParamSignUp) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserLogicInterface creates a new instance of UserLogicInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserLogicInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserLogicInterface {
	mock := &UserLogicInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
